/**
 * setup.ts
 *
 * Purpose:
 * - Global setup file for Vitest tests in the UI application.
 * - Configures the testing environment, mocks browser APIs, and sets up global variables.
 *
 * Logic Overview:
 * 1. Imports `@testing-library/jest-dom/vitest` for extended DOM matchers.
 * 2. Uses `beforeAll` to set up `window.TDS_CONFIG` to simulate runtime configuration, making tests independent of actual API endpoints.
 * 3. Mocks `window.matchMedia` to prevent errors related to media queries in a JSDOM environment.
 * 4. Mocks `ResizeObserver` to avoid errors when components use this API.
 * 5. Mocks `react-i18next` to provide a simplified `t` function for translations and mock `I18nextProvider`, ensuring tests don't rely on actual translation files.
 *
 * Last Updated:
 * 2025-07-16 by Cline (Added file header documentation)
 */
/* eslint-disable @typescript-eslint/no-empty-function */

import '@testing-library/jest-dom/vitest';

import { beforeAll, vi } from 'vitest';

// Extend the Window interface to include properties that might be mocked or added
declare global {
  interface Window {
    TDS_CONFIG: {
      API_URL: string;
    };
  }
}

// Mock the runtime configuration object for all tests.
// This simulates the config.js file that is generated by Docker at runtime.
beforeAll(() => {
  window.TDS_CONFIG = {
    // You can use any valid URL here for testing purposes.
    // Check apps/ui/tds-bookmark-manager-ui/public/config.js
    // This makes the tests independent of any real endpoint.
    API_URL: 'https://api.test-host.com/v1'
  };
});

// Mock window.matchMedia
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

// Mock ResizeObserver
global.ResizeObserver = class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
};

// Mock react-i18next
vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string) => key, // Mock t function to return the key itself
    i18n: {
      changeLanguage: vi.fn(),
    },
  }),
  initReactI18next: {
    type: '3rdParty',
    init: vi.fn(),
  },
  I18nextProvider: ({ children }: { children: React.ReactNode }) => children, // Mock I18nextProvider
}));
