services:
  tds-bookmark-manager:
    image: registry.thedavestack.com/tds-bookmark-manager:latest
    container_name: tds-bookmark-manager
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tds-bookmark-manager-app.rule=Host(`tds-bookmark-manager.thedavestack.com`)"
      - "traefik.http.routers.tds-bookmark-manager-app.entrypoints=websecure"
      - "traefik.http.routers.tds-bookmark-manager-app.tls=true"
      - "traefik.http.routers.tds-bookmark-manager-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tds-bookmark-manager-app.middlewares=tds-bookmark-manager-auth"
      - "traefik.http.services.tds-bookmark-manager-app.loadbalancer.server.port=80"
      - "traefik.http.middlewares.tds-bookmark-manager-auth.basicauth.users=telco2011:$2y$05$qO7QbEWBy/3wl4TZiUTE1OVuYZSd8Pn7j/xthInlANJtHtsDgw9iO"